// 资本动作数据 - 2026-08-03 16:01
window.__CAPITAL_DATA__ = {
  "2026-08-03": [
    {
      "id": "1225455977",
      "code": "02068",
      "name": "中铝国际",
      "city": "未知",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "<em>股权激励</em>部分限制性股票回购注销实施",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455977.PDF"
    },
    {
      "id": "1225453073",
      "code": "002955",
      "name": "鸿合科技",
      "city": "北京",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股票期权",
      "summary": "董事会薪酬与考核委员会关于公司2026年<em>股票期权激励</em>计划激励对象名单的审核意见及公示情况说明",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453073.PDF"
    },
    {
      "id": "1225455979",
      "code": "02068",
      "name": "中铝国际",
      "city": "未知",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "北京市嘉源律师事务所关于中铝国际工程股份有限公司2023年<em>限制性</em><em>股票</em>激励计划部分<em>限制性</em><em>股票</em>回购注销实施情况的法律意见书",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455979.PDF"
    },
    {
      "id": "1225455229",
      "code": "300395",
      "name": "菲利华",
      "city": "湖北荆州沙",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "湖北今天律师事务所关于湖北菲利华石英玻璃股份有限公司2025年<em>限制性</em><em>股票</em>激励计划预留部分授予事项的法律意见书",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455229.PDF"
    },
    {
      "id": "1225455227",
      "code": "300395",
      "name": "菲利华",
      "city": "湖北荆州沙",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于向激励对象授予预留部分<em>限制性</em><em>股票</em>的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455227.PDF"
    },
    {
      "id": "1225455230",
      "code": "300395",
      "name": "菲利华",
      "city": "湖北荆州沙",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "董事会薪酬与考核委员会关于2025年<em>限制性</em><em>股票</em>激励计划预留授予相关事项的核查意见",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455230.PDF"
    },
    {
      "id": "1225455228",
      "code": "300395",
      "name": "菲利华",
      "city": "湖北荆州沙",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "2025年<em>限制性</em><em>股票</em>激励计划预留授予激励对象名单 预留授予日",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455228.PDF"
    },
    {
      "id": "1225454146",
      "code": "300232",
      "name": "洲明科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于2024年<em>限制性</em><em>股票</em>激励计划首次及预留授予第一个归属期 第一批次 归属结果暨股份上市的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454146.PDF"
    },
    {
      "id": "1225453792",
      "code": "300707",
      "name": "威唐工业",
      "city": "江苏无锡",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "关于2024年<em>限制性</em><em>股票</em>激励计划部分<em>限制性</em><em>股票</em>回购注销完成的公告",
      "date": "2026-08-03",
      "star": 4,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453792.PDF"
    },
    {
      "id": "1225456170",
      "code": "03288",
      "name": "海天味业",
      "city": "未知",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "海外监管公告 - 海天味业关于2024年<em>员工</em><em>持股</em>计划A股股份回购注销实施公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456170.PDF"
    },
    {
      "id": "1225455683",
      "code": "300541",
      "name": "先进数通",
      "city": "北京",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "先进数通2026年<em>员工</em><em>持股</em>计划第一次持有人会议决议公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455683.PDF"
    },
    {
      "id": "1225454619",
      "code": "300875",
      "name": "捷强装备",
      "city": "天津",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "2026年<em>员工</em><em>持股</em>计划第一次持有人会议决议公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454619.PDF"
    },
    {
      "id": "1225453600",
      "code": "301280",
      "name": "珠城科技",
      "city": "浙江温州乐清",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于2024年<em>员工</em><em>持股</em>计划首次授予部分第二个锁定期届满暨解锁条件成就的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453600.PDF"
    },
    {
      "id": "1225456174",
      "code": "301160",
      "name": "翔楼新材",
      "city": "江苏苏州",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于5%以上股东 董事 高级管理人员提前终止<em>减持</em>计划暨<em>减持</em>股份结果的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456174.PDF"
    },
    {
      "id": "1225454350",
      "code": "301042",
      "name": "安联锐视",
      "city": "广东珠海",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于回购股份集中竞价<em>减持</em>计划的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454350.PDF"
    },
    {
      "id": "1225454144",
      "code": "301300",
      "name": "远翔新材",
      "city": "福建南平邵武",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于回购股份集中竞价<em>减持</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454144.PDF"
    },
    {
      "id": "1225453741",
      "code": "301125",
      "name": "腾亚精工",
      "city": "江苏南京",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于回购股份集中竞价<em>减持</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453741.PDF"
    },
    {
      "id": "1225453740",
      "code": "300835",
      "name": "龙磁科技",
      "city": "安徽合肥",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于以集中竞价方式<em>减持</em>已回购股份进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453740.PDF"
    },
    {
      "id": "1225456420",
      "code": "02147",
      "name": "正味集团",
      "city": "未知",
      "mv": 0,
      "category": "增减持",
      "subType": "增持",
      "summary": "建议<em>增</em>加法定股本及建议按于记录日期每<em>持</em>有一(1) 股股份获发六(6) 股供股股份的基准以非包销基准进行供股",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456420.PDF"
    },
    {
      "id": "1225453833",
      "code": "300665",
      "name": "飞鹿股份",
      "city": "湖南株洲",
      "mv": 0,
      "category": "增减持",
      "subType": "增持",
      "summary": "关于公司控股股东<em>增</em><em>持</em>公司股份计划暨取得金融机构<em>增</em><em>持</em>贷款承诺函的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453833.PDF"
    },
    {
      "id": "1225456390",
      "code": "08279",
      "name": "亚博科技控股",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "股东周年大会通告 发行及<em>回购</em><em>股份</em>之一般授权 重选董事 建议更改公司名称 建议修订公司细则及建议采纳新公司细则",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456390.PDF"
    },
    {
      "id": "1225456375",
      "code": "09980",
      "name": "东鹏饮料",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告 - 关于以集中竞价交易方式<em>回购</em>A股<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456375.PDF"
    },
    {
      "id": "1225456304",
      "code": "00564",
      "name": "中创智领",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "中创智领 郑州 工业技术集团<em>股份</em>有限公司关于<em>回购</em><em>股份</em>事项前十大股东和前十大无限售条件股东持股情况的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456304.PDF"
    },
    {
      "id": "1225456283",
      "code": "06951",
      "name": "三环集团",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告 - 关于首次<em>回购</em>公司<em>股份</em>暨<em>回购</em>公司<em>股份</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456283.PDF"
    },
    {
      "id": "1225456218",
      "code": "09995",
      "name": "荣昌生物",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告 - 关于2026年第一次以集中竞价交易方式<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456218.PDF"
    },
    {
      "id": "1225456086",
      "code": "300408",
      "name": "三环集团",
      "city": "广东潮州",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于首次<em>回购</em>公司<em>股份</em>暨<em>回购</em>公司<em>股份</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456086.PDF"
    },
    {
      "id": "1225456161",
      "code": "03288",
      "name": "海天味业",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告 - 海天味业关于<em>回购</em>公司A股<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456161.PDF"
    },
    {
      "id": "1225456082",
      "code": "300274",
      "name": "阳光电源",
      "city": "安徽合肥",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>方案的公告暨<em>回购</em><em>股份</em>报告书",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456082.PDF"
    },
    {
      "id": "1225456079",
      "code": "300631",
      "name": "久吾高科",
      "city": "江苏南京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "<em>回购</em><em>股份</em>报告书公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456079.PDF"
    },
    {
      "id": "1225456080",
      "code": "300631",
      "name": "久吾高科",
      "city": "江苏南京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>方案的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456080.PDF"
    },
    {
      "id": "1225456075",
      "code": "300347",
      "name": "泰格医药",
      "city": "浙江杭州",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456075.PDF"
    },
    {
      "id": "1225456051",
      "code": "300232",
      "name": "洲明科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>方案的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456051.PDF"
    },
    {
      "id": "1225456037",
      "code": "300132",
      "name": "青松<em>股份</em>",
      "city": "广东中山",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>用于注销并减少注册资本暨通知债权人的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456037.PDF"
    },
    {
      "id": "1225456031",
      "code": "300132",
      "name": "青松<em>股份</em>",
      "city": "广东中山",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "<em>回购</em>报告书",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456031.PDF"
    },
    {
      "id": "1225456028",
      "code": "06809",
      "name": "澜起科技",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告-关于以集中竞价交易方式<em>回购</em>A股<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456028.PDF"
    },
    {
      "id": "1225455971",
      "code": "03347",
      "name": "泰格医药",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告 - 关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455971.PDF"
    },
    {
      "id": "1225455837",
      "code": "02050",
      "name": "三花智控",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告-浙江三花智能控制<em>股份</em>有限公司关于<em>回购</em>公司A股<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455837.PDF"
    },
    {
      "id": "1225455794",
      "code": "03296",
      "name": "华勤技术",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告 - 以集中竞价交易方式<em>回购</em>公司A股<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455794.PDF"
    },
    {
      "id": "1225455770",
      "code": "02475",
      "name": "立讯精密",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告 - 关于<em>股份</em><em>回购</em>进展情况的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455770.PDF"
    },
    {
      "id": "1225454145",
      "code": "300691",
      "name": "联合光电",
      "city": "广东中山",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454145.PDF"
    },
    {
      "id": "1225455566",
      "code": "01688",
      "name": "领益智造",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告-关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455566.PDF"
    },
    {
      "id": "1225455262",
      "code": "300162",
      "name": "雷曼光电",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于出售已<em>回购</em><em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455262.PDF"
    },
    {
      "id": "1225455231",
      "code": "300532",
      "name": "今天国际",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455231.PDF"
    },
    {
      "id": "1225455217",
      "code": "300095",
      "name": "华伍<em>股份</em>",
      "city": "江西宜春丰城",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "<em>回购</em><em>股份</em>报告书",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455217.PDF"
    },
    {
      "id": "1225455214",
      "code": "301275",
      "name": "汉朔科技",
      "city": "浙江嘉兴",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455214.PDF"
    },
    {
      "id": "1225455218",
      "code": "300095",
      "name": "华伍<em>股份</em>",
      "city": "江西宜春丰城",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em><em>股份</em>进展情况的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455218.PDF"
    },
    {
      "id": "1225455318",
      "code": "09611",
      "name": "龙旗科技",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告 - 关于以集中竞价交易方式<em>回购</em><em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455318.PDF"
    },
    {
      "id": "1225455215",
      "code": "300138",
      "name": "晨光生物",
      "city": "河北邯郸",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455215.PDF"
    },
    {
      "id": "1225455156",
      "code": "300296",
      "name": "利亚德",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>股份</em><em>回购</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455156.PDF"
    },
    {
      "id": "1225455154",
      "code": "300624",
      "name": "万兴科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455154.PDF"
    },
    {
      "id": "1225454669",
      "code": "300304",
      "name": "云意电气",
      "city": "江苏徐州",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454669.PDF"
    },
    {
      "id": "1225454745",
      "code": "00219",
      "name": "顺豪物业",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "联合公告 - (1) 顺豪物业投资有限公司之<em>股份</em>转让: (2) 可能进行之场外<em>股份</em><em>回购</em>; 及(3)特别股息建议之月度更新",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454745.PDF"
    },
    {
      "id": "1225454616",
      "code": "300253",
      "name": "卫宁健康",
      "city": "上海",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em><em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454616.PDF"
    },
    {
      "id": "1225454685",
      "code": "00201",
      "name": "华大酒店",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "联合公告 - (1) 顺豪物业投资有限公司之<em>股份</em>转让; (2) 可能进行之场外<em>股份</em><em>回购</em>; 及 (3) 特别股息建议之月度更新",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454685.PDF"
    },
    {
      "id": "1225454613",
      "code": "301320",
      "name": "豪江智能",
      "city": "山东青岛",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454613.PDF"
    },
    {
      "id": "1225454542",
      "code": "300122",
      "name": "智飞生物",
      "city": "重庆",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454542.PDF"
    },
    {
      "id": "1225454541",
      "code": "300676",
      "name": "华大基因",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于第三期以集中竞价交易方式<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454541.PDF"
    },
    {
      "id": "1225454537",
      "code": "300036",
      "name": "超图软件",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454537.PDF"
    },
    {
      "id": "1225454538",
      "code": "301252",
      "name": "同星科技",
      "city": "浙江绍兴",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于首次<em>回购</em>公司<em>股份</em>暨<em>回购</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454538.PDF"
    },
    {
      "id": "1225454540",
      "code": "300679",
      "name": "电连技术",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454540.PDF"
    },
    {
      "id": "1225454624",
      "code": "00386",
      "name": "中国石油化工<em>股份</em>",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告 - 中国石油化工<em>股份</em>有限公司关于以集中竞价交易方式<em>回购</em>A股<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454624.PDF"
    },
    {
      "id": "1225454406",
      "code": "300843",
      "name": "胜蓝<em>股份</em>",
      "city": "广东东莞",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于取得金融机构股票<em>回购</em>专项贷款承诺函的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454406.PDF"
    },
    {
      "id": "1225454404",
      "code": "301396",
      "name": "宏景科技",
      "city": "广东广州",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>方案的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454404.PDF"
    },
    {
      "id": "1225454405",
      "code": "300843",
      "name": "胜蓝<em>股份</em>",
      "city": "广东东莞",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>方案的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454405.PDF"
    },
    {
      "id": "1225454349",
      "code": "300971",
      "name": "博亚精工",
      "city": "湖北襄阳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454349.PDF"
    },
    {
      "id": "1225454345",
      "code": "301511",
      "name": "德福科技",
      "city": "江西九江",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em><em>股份</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454345.PDF"
    },
    {
      "id": "1225454348",
      "code": "300783",
      "name": "三只松鼠",
      "city": "安徽芜湖",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454348.PDF"
    },
    {
      "id": "1225454000",
      "code": "301498",
      "name": "乖宝宠物",
      "city": "山东聊城",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em><em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454000.PDF"
    },
    {
      "id": "1225453922",
      "code": "300802",
      "name": "矩子科技",
      "city": "上海",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453922.PDF"
    },
    {
      "id": "1225453921",
      "code": "300888",
      "name": "稳健医疗",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453921.PDF"
    },
    {
      "id": "1225453747",
      "code": "301115",
      "name": "联检科技",
      "city": "江苏常州",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453747.PDF"
    },
    {
      "id": "1225453744",
      "code": "301236",
      "name": "软通动力",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453744.PDF"
    },
    {
      "id": "1225453831",
      "code": "301223",
      "name": "中荣<em>股份</em>",
      "city": "广东中山",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>股份</em><em>回购</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453831.PDF"
    },
    {
      "id": "1225453984",
      "code": "00525",
      "name": "广深铁路<em>股份</em>",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "于其他市场发布的公告- 广深铁路关于以集中竞价交易方式<em>回购</em>公司 A 股<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453984.PDF"
    },
    {
      "id": "1225453798",
      "code": "300203",
      "name": "聚光科技",
      "city": "浙江杭州",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453798.PDF"
    },
    {
      "id": "1225453804",
      "code": "300592",
      "name": "华凯易佰",
      "city": "湖南长沙",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于首次<em>回购</em>公司<em>股份</em>暨<em>回购</em><em>股份</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453804.PDF"
    },
    {
      "id": "1225453796",
      "code": "300982",
      "name": "苏文电能",
      "city": "江苏常州",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453796.PDF"
    },
    {
      "id": "1225453794",
      "code": "300707",
      "name": "威唐工业",
      "city": "江苏无锡",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453794.PDF"
    },
    {
      "id": "1225453805",
      "code": "300592",
      "name": "华凯易佰",
      "city": "湖南长沙",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em><em>股份</em>事项前十大股东和前十大无限售条件股东持股情况的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453805.PDF"
    },
    {
      "id": "1225453793",
      "code": "300707",
      "name": "威唐工业",
      "city": "江苏无锡",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em><em>股份</em>注销完成调整可转债转股价格的公告",
      "date": "2026-08-03",
      "star": 4,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453793.PDF"
    },
    {
      "id": "1225453800",
      "code": "300774",
      "name": "倍杰特",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453800.PDF"
    },
    {
      "id": "1225453795",
      "code": "300124",
      "name": "汇川技术",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453795.PDF"
    },
    {
      "id": "1225453746",
      "code": "300491",
      "name": "通合科技",
      "city": "河北石家庄",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453746.PDF"
    },
    {
      "id": "1225453599",
      "code": "300871",
      "name": "回盛生物",
      "city": "湖北武汉",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453599.PDF"
    },
    {
      "id": "1225453610",
      "code": "301501",
      "name": "恒鑫生活",
      "city": "安徽合肥",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>股份</em><em>回购</em>进展情况的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453610.PDF"
    },
    {
      "id": "1225453597",
      "code": "300787",
      "name": "海能实业",
      "city": "江西吉安",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453597.PDF"
    },
    {
      "id": "1225453584",
      "code": "301086",
      "name": "鸿富瀚",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453584.PDF"
    },
    {
      "id": "1225453582",
      "code": "301004",
      "name": "嘉益<em>股份</em>",
      "city": "浙江金华",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453582.PDF"
    },
    {
      "id": "1225453579",
      "code": "301322",
      "name": "绿通科技",
      "city": "广东东莞",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于第三期<em>回购</em>公司<em>股份</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453579.PDF"
    },
    {
      "id": "1225453559",
      "code": "301186",
      "name": "超达装备",
      "city": "江苏南通如皋",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>股份</em><em>回购</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453559.PDF"
    },
    {
      "id": "1225453529",
      "code": "301263",
      "name": "泰恩康",
      "city": "广东汕头",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453529.PDF"
    },
    {
      "id": "1225453499",
      "code": "301173",
      "name": "毓恬冠佳",
      "city": "上海",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>股份</em><em>回购</em>进展情况的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453499.PDF"
    },
    {
      "id": "1225453530",
      "code": "301318",
      "name": "维海德",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453530.PDF"
    },
    {
      "id": "1225453498",
      "code": "301265",
      "name": "华新科技",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453498.PDF"
    },
    {
      "id": "1225453452",
      "code": "301367",
      "name": "瑞迈特",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453452.PDF"
    },
    {
      "id": "1225453428",
      "code": "301097",
      "name": "天益医疗",
      "city": "浙江宁波",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453428.PDF"
    },
    {
      "id": "1225453398",
      "code": "300832",
      "name": "新产业",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>股份</em><em>回购</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453398.PDF"
    },
    {
      "id": "1225453376",
      "code": "300463",
      "name": "迈克生物",
      "city": "四川成都",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453376.PDF"
    },
    {
      "id": "1225453372",
      "code": "300482",
      "name": "万孚生物",
      "city": "广东广州",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>实施结果暨<em>股份</em>变动的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453372.PDF"
    },
    {
      "id": "1225453374",
      "code": "301305",
      "name": "朗坤科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于首次<em>回购</em>公司<em>股份</em>暨<em>回购</em>进展的公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453374.PDF"
    },
    {
      "id": "1225453373",
      "code": "301166",
      "name": "优宁维",
      "city": "上海",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-03",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453373.PDF"
    },
    {
      "id": "1225456126",
      "code": "02465",
      "name": "龙蟠科技",
      "city": "未知",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "海外监管公告 - 关于使用<em>闲置</em>募集<em>资金</em>进行现金管理赎回的进展公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456126.PDF"
    },
    {
      "id": "1225455486",
      "code": "300864",
      "name": "南大环境",
      "city": "江苏南京",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用暂时<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455486.PDF"
    },
    {
      "id": "1225455219",
      "code": "300395",
      "name": "菲利华",
      "city": "湖北荆州沙",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分暂时<em>闲置</em>募集<em>资金</em>进行现金管理的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455219.PDF"
    },
    {
      "id": "1225455220",
      "code": "300395",
      "name": "菲利华",
      "city": "湖北荆州沙",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "长江证券承销保荐有限公司关于湖北菲利华石英玻璃股份有限公司使用部分暂时<em>闲置</em>募集<em>资金</em>进行现金管理的核查意见",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455220.PDF"
    },
    {
      "id": "1225454739",
      "code": "300648",
      "name": "星云股份",
      "city": "福建福州",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>进行现金管理到期赎回的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454739.PDF"
    },
    {
      "id": "1225454618",
      "code": "300762",
      "name": "上海瀚讯",
      "city": "上海",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454618.PDF"
    },
    {
      "id": "1225454003",
      "code": "300565",
      "name": "科信技术",
      "city": "广东深圳",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>进行现金管理到期赎回的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454003.PDF"
    },
    {
      "id": "1225453803",
      "code": "301206",
      "name": "三元生物",
      "city": "山东滨州",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于继续使用暂时<em>闲置</em>超募<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453803.PDF"
    },
    {
      "id": "1225453670",
      "code": "301098",
      "name": "金埔园林",
      "city": "江苏南京",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分暂时<em>闲置</em>募集<em>资金</em>进行现金管理到期赎回的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453670.PDF"
    },
    {
      "id": "1225453598",
      "code": "301000",
      "name": "肇民科技",
      "city": "上海",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用<em>闲置</em>募集<em>资金</em>和自有<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453598.PDF"
    },
    {
      "id": "1225453587",
      "code": "301193",
      "name": "家联科技",
      "city": "浙江宁波",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于归还暂时补充流动<em>资金</em>的<em>闲置</em>募集<em>资金</em>的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453587.PDF"
    },
    {
      "id": "1225453578",
      "code": "300501",
      "name": "海顺新材",
      "city": "上海",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453578.PDF"
    },
    {
      "id": "1225453454",
      "code": "300879",
      "name": "大叶股份",
      "city": "浙江宁波余姚",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于归还用于暂时补充流动<em>资金</em>的<em>闲置</em>募集<em>资金</em>的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453454.PDF"
    },
    {
      "id": "1225454932",
      "code": "301085",
      "name": "亚康股份",
      "city": "北京",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "协议转让",
      "summary": "关于实际控制人之一致行动人<em>协议</em><em>转让</em>部分股份过户完成登记的公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454932.PDF"
    },
    {
      "id": "1225454148",
      "code": "300437",
      "name": "清水源",
      "city": "河南济源",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "股权转让",
      "summary": "关于<em>转让</em>全资子公司部分<em>股权</em>的进展公告",
      "date": "2026-08-03",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454148.PDF"
    }
  ],
  "2026-08-02": [
    {
      "id": "1225452774",
      "code": "603400",
      "name": "华之杰",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "北京市天元律师事务所关于苏州华之杰电讯股份有限公司2026年<em>股票期权激励</em>计划授予数量及行权价格调整相关事项的法律意见",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225452774.PDF"
    },
    {
      "id": "1225452771",
      "code": "603400",
      "name": "华之杰",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "华之杰关于调整2026年<em>股票期权激励</em>计划授予数量及行权价格的公告",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225452771.PDF"
    },
    {
      "id": "1225452768",
      "code": "603400",
      "name": "华之杰",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "华之杰董事会薪酬与考核委员会关于调整2026年<em>股票期权激励</em>计划授予数量及行权价格相关事项的核查意见",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225452768.PDF"
    },
    {
      "id": "1225450270",
      "code": "301366",
      "name": "一博科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于调整2026年<em>限制性</em><em>股票</em>激励计划授予价格的公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225450270.PDF"
    },
    {
      "id": "1225450269",
      "code": "301366",
      "name": "一博科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "广东信达律师事务所关于深圳市一博科技股份有限公司2026年<em>限制性</em><em>股票</em>激励计划授予价格调整事项的法律意见书",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225450269.PDF"
    },
    {
      "id": "1225450182",
      "code": "301156",
      "name": "美农生物",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "2025年<em>限制性</em><em>股票</em>激励计划第一个归属期归属结果暨股份上市公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225450182.PDF"
    },
    {
      "id": "1225456053",
      "code": "920237",
      "name": "力佳科技",
      "city": "湖北宜昌",
      "mv": 0,
      "category": "增减持",
      "subType": "减持计划",
      "summary": "股东拟<em>减持</em>股份的预披露公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456053.PDF"
    },
    {
      "id": "1225452778",
      "code": "300615",
      "name": "欣天科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于持股5%以上股东未<em>减持</em>股份并提前终止股份<em>减持</em>计划的公告",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225452778.PDF"
    },
    {
      "id": "1225454177",
      "code": "920163",
      "name": "方大新材",
      "city": "河北石家庄",
      "mv": 0,
      "category": "增减持",
      "subType": "增持",
      "summary": "关于董事会秘书<em>增</em><em>持</em>股份结果公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454177.PDF"
    },
    {
      "id": "1225451425",
      "code": "002601",
      "name": "龙佰集团",
      "city": "河南焦作",
      "mv": 0,
      "category": "增减持",
      "subType": "增持",
      "summary": "关于公司控股股东 部分董事 高级管理人员及核心骨干员工<em>增</em><em>持</em>公司股份计划实施完毕暨<em>增</em><em>持</em>结果的公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225451425.PDF"
    },
    {
      "id": "1225456124",
      "code": "920429",
      "name": "康比特",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "<em>回购</em>进展情况暨<em>回购</em><em>股份</em>累计达1%公告",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225456124.PDF"
    },
    {
      "id": "1225455011",
      "code": "920703",
      "name": "广厦环能",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "<em>回购</em><em>股份</em>结果公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455011.PDF"
    },
    {
      "id": "1225454671",
      "code": "920374",
      "name": "云里物里",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "第三次竞价<em>回购</em><em>股份</em>进展情况公告",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454671.PDF"
    },
    {
      "id": "1225454634",
      "code": "920717",
      "name": "瑞星<em>股份</em>",
      "city": "河北衡水",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "<em>回购</em>进展情况公告",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454634.PDF"
    },
    {
      "id": "1225453814",
      "code": "920689",
      "name": "克莱特",
      "city": "山东威海",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "<em>回购</em><em>股份</em>报告书公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225453814.PDF"
    },
    {
      "id": "1225452770",
      "code": "688623",
      "name": "双元科技",
      "city": "浙江杭州",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em><em>股份</em>事项前十名股东和前十名无限售条件股东持股情况的公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225452770.PDF"
    },
    {
      "id": "1225452754",
      "code": "688303",
      "name": "大全能源",
      "city": "新疆维吾尔自治区石河子",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "大全能源关于实施<em>回购</em><em>股份</em>注销暨<em>股份</em>变动的公告",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225452754.PDF"
    },
    {
      "id": "1225452752",
      "code": "688207",
      "name": "格灵深瞳",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "格灵深瞳关于以集中竞价交易方式<em>回购</em>公司<em>股份</em>比例达到总股本1%暨<em>股份</em><em>回购</em>进展公告",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225452752.PDF"
    },
    {
      "id": "1225452746",
      "code": "600109",
      "name": "国金证券",
      "city": "四川成都",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "国金证券<em>股份</em>有限公司关于<em>股份</em><em>回购</em>进展公告",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225452746.PDF"
    },
    {
      "id": "1225452741",
      "code": "603725",
      "name": "天安新材",
      "city": "广东佛山",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "天安新材关于以集中竞价交易方式<em>回购</em><em>股份</em>方案的公告",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225452741.PDF"
    },
    {
      "id": "1225452736",
      "code": "688623",
      "name": "双元科技",
      "city": "浙江杭州",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于以集中竞价交易方式<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225452736.PDF"
    },
    {
      "id": "1225450670",
      "code": "301360",
      "name": "荣旗科技",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>的进展公告",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225450670.PDF"
    },
    {
      "id": "1225450628",
      "code": "000688",
      "name": "国城矿业",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于首次<em>回购</em>公司<em>股份</em>暨<em>回购</em>进展的公告",
      "date": "2026-08-02",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225450628.PDF"
    },
    {
      "id": "1225455941",
      "code": "920083",
      "name": "金戈新材",
      "city": "未知",
      "mv": 0,
      "category": "委托理财",
      "subType": "委托理财",
      "summary": "关于使用闲置自有资金进行<em>委托</em><em>理财</em>的公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455941.PDF"
    },
    {
      "id": "1225455939",
      "code": "920083",
      "name": "金戈新材",
      "city": "未知",
      "mv": 0,
      "category": "委托理财",
      "subType": "委托理财",
      "summary": "中国国际金融股份有限公司关于广东金戈新材料股份有限公司使用闲置自有资金进行<em>委托</em><em>理财</em>的核查意见",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455939.PDF"
    },
    {
      "id": "1225455235",
      "code": "920227",
      "name": "美登科技",
      "city": "浙江杭州",
      "mv": 0,
      "category": "委托理财",
      "subType": "委托理财",
      "summary": "自有资金<em>委托</em><em>理财</em>进展公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225455235.PDF"
    },
    {
      "id": "1225454632",
      "code": "920078",
      "name": "族兴新材",
      "city": "湖南长沙宁乡",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分暂时<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454632.PDF"
    },
    {
      "id": "1225454189",
      "code": "920976",
      "name": "视声智能",
      "city": "广东广州",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用<em>闲置</em>自有<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454189.PDF"
    },
    {
      "id": "1225454180",
      "code": "920211",
      "name": "新睿电子",
      "city": "未知",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分暂时<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454180.PDF"
    },
    {
      "id": "1225454178",
      "code": "920679",
      "name": "前进科技",
      "city": "浙江丽水",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454178.PDF"
    },
    {
      "id": "1225454176",
      "code": "920136",
      "name": "永励精密",
      "city": "未知",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225454176.PDF"
    },
    {
      "id": "1225450276",
      "code": "301366",
      "name": "一博科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "中国国际金融股份有限公司关于深圳市一博科技股份有限公司使用部分<em>闲置</em>募集<em>资金</em>临时补充流动<em>资金</em>的核查意见",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225450276.PDF"
    },
    {
      "id": "1225450275",
      "code": "301366",
      "name": "一博科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>临时补充流动<em>资金</em>的公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225450275.PDF"
    },
    {
      "id": "1225452780",
      "code": "300615",
      "name": "欣天科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "协议转让",
      "summary": "关于控股股东 实际控制人及相关方签署股份<em>转让</em><em>协议</em>暨控制权拟发生变更的提示性公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225452780.PDF"
    },
    {
      "id": "1225452779",
      "code": "300615",
      "name": "欣天科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "控制权变更",
      "summary": "关于筹划公司<em>控制权</em><em>变更</em>事项进展暨复牌的公告",
      "date": "2026-08-02",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-03/1225452779.PDF"
    }
  ]
};
