// 资本动作数据 - 2026-08-10 14:35
window.__CAPITAL_DATA__ = {
  "2026-08-10": [
    {
      "id": "1225466521",
      "code": "301018",
      "name": "申菱环境",
      "city": "广东佛山",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励",
      "summary": "创业板上市公司<em>股权激励</em>计划自查表",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466521.PDF"
    },
    {
      "id": "1225465471",
      "code": "301488",
      "name": "豪恩汽电",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于2024年<em>股票期权激励</em>计划首次授予第二个行权期第二批次期权行权条件成就的公告",
      "date": "2026-08-10",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465471.PDF"
    },
    {
      "id": "1225465473",
      "code": "301488",
      "name": "豪恩汽电",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "北京市通商 深圳 律师事务所关于深圳市豪恩汽车电子装备股份有限公司2024年<em>股票期权激励</em>计划首次授予第二个行权期第二批次期权行权条件成就的法律意见书",
      "date": "2026-08-10",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465473.PDF"
    },
    {
      "id": "1225467220",
      "code": "300508",
      "name": "维宏股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "2023年<em>限制性</em><em>股票</em>激励计划授予价格调整 第三个归属期归属条件成就暨部分<em>限制性</em><em>股票</em>作废之法律意见书",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467220.PDF"
    },
    {
      "id": "1225467219",
      "code": "300508",
      "name": "维宏股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "2024年<em>限制性</em><em>股票</em>激励计划授予价格调整 首次及预留授予第二个归属期归属条件成就暨部分<em>限制性</em><em>股票</em>作废之法律意见书",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467219.PDF"
    },
    {
      "id": "1225467218",
      "code": "300508",
      "name": "维宏股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "董事会薪酬与考核委员会关于2024年<em>限制性</em><em>股票</em>激励计划首次及预留授予第二个归属期归属名单的核查意见",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467218.PDF"
    },
    {
      "id": "1225467217",
      "code": "300508",
      "name": "维宏股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "董事会薪酬与考核委员会关于2023年<em>限制性</em><em>股票</em>激励计划第三个归属期归属名单的核查意见",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467217.PDF"
    },
    {
      "id": "1225467216",
      "code": "300508",
      "name": "维宏股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于调整2023年<em>限制性</em><em>股票</em>激励计划授予价格的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467216.PDF"
    },
    {
      "id": "1225467215",
      "code": "300508",
      "name": "维宏股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于2024年<em>限制性</em><em>股票</em>激励计划首次及预留授予第二个归属期符合归属条件的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467215.PDF"
    },
    {
      "id": "1225467214",
      "code": "300508",
      "name": "维宏股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "关于2023年<em>限制性</em><em>股票</em>激励计划第三个归属期符合归属条件的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467214.PDF"
    },
    {
      "id": "1225467213",
      "code": "300508",
      "name": "维宏股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于调整2024年<em>限制性</em><em>股票</em>激励计划授予价格的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467213.PDF"
    },
    {
      "id": "1225467212",
      "code": "300508",
      "name": "维宏股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于作废2023年<em>限制性</em><em>股票</em>激励计划部分已授予尚未归属的<em>限制性</em><em>股票</em>的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467212.PDF"
    },
    {
      "id": "1225467211",
      "code": "300508",
      "name": "维宏股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于作废2024年<em>限制性</em><em>股票</em>激励计划部分已授予尚未归属的<em>限制性</em><em>股票</em>的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467211.PDF"
    },
    {
      "id": "1225467188",
      "code": "300097",
      "name": "智云股份",
      "city": "辽宁大连",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于2026年<em>限制性</em><em>股票</em>激励计划首次授予登记完成的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467188.PDF"
    },
    {
      "id": "1225466523",
      "code": "301018",
      "name": "申菱环境",
      "city": "广东佛山",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "北京国枫律师事务所关于广东申菱环境系统股份有限公司第三期<em>限制性</em><em>股票</em>激励计划的法律意见书",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466523.PDF"
    },
    {
      "id": "1225466518",
      "code": "301018",
      "name": "申菱环境",
      "city": "广东佛山",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "第三期<em>限制性</em><em>股票</em>激励计划 草案 摘要",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466518.PDF"
    },
    {
      "id": "1225466522",
      "code": "301018",
      "name": "申菱环境",
      "city": "广东佛山",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "广东申菱环境系统股份有限公司董事会薪酬与考核委员会关于公司第三期<em>限制性</em><em>股票</em>激励计划相关事项的核查意见",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466522.PDF"
    },
    {
      "id": "1225466519",
      "code": "301018",
      "name": "申菱环境",
      "city": "广东佛山",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "第三期<em>限制性</em><em>股票</em>激励计划 草案",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466519.PDF"
    },
    {
      "id": "1225466525",
      "code": "301018",
      "name": "申菱环境",
      "city": "广东佛山",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "关于暂不召开股东会审议第三期<em>限制性</em><em>股票</em>激励计划相关事宜的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466525.PDF"
    },
    {
      "id": "1225466520",
      "code": "301018",
      "name": "申菱环境",
      "city": "广东佛山",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "第三期<em>限制性</em><em>股票</em>激励计划考核管理办法",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466520.PDF"
    },
    {
      "id": "1225466131",
      "code": "300507",
      "name": "苏奥传感",
      "city": "江苏扬州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于2022年<em>限制性</em><em>股票</em>激励计划首次授予部分第三个归属期及预留授予部分第二个归属期归属结果暨股份上市的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466131.PDF"
    },
    {
      "id": "1225466031",
      "code": "301336",
      "name": "趣睡科技",
      "city": "四川成都",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "成都趣睡科技股份有限公司关于2026年<em>限制性</em><em>股票</em>激励计划内幕信息知情人及激励对象买卖公司<em>股票</em>情况的自查报告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466031.PDF"
    },
    {
      "id": "1225466032",
      "code": "301336",
      "name": "趣睡科技",
      "city": "四川成都",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "成都趣睡科技股份有限公司董事会薪酬与考核委员会关于公司2026年<em>限制性</em><em>股票</em>激励计划激励对象名单的核查意见及公示情况说明",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466032.PDF"
    },
    {
      "id": "1225465583",
      "code": "300852",
      "name": "四会富仕",
      "city": "广东肇庆四会",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "关于2026年<em>限制性</em><em>股票</em>激励计划内幕信息知情人买卖公司<em>股票</em>情况的自查报告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465583.PDF"
    },
    {
      "id": "1225465450",
      "code": "301319",
      "name": "唯特偶",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股票期权",
      "summary": "关于部分<em>股票</em><em>期权</em>注销完成的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465450.PDF"
    },
    {
      "id": "1225467417",
      "code": "300521",
      "name": "爱司凯",
      "city": "广东广州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "陕国投·爱司凯2026年<em>员工</em><em>持股</em>集合资金信托计划信托合同",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467417.PDF"
    },
    {
      "id": "1225467418",
      "code": "300521",
      "name": "爱司凯",
      "city": "广东广州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "关于2026年<em>员工</em><em>持股</em>计划实施进展的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467418.PDF"
    },
    {
      "id": "1225467408",
      "code": "300689",
      "name": "澄天伟业",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "关于选举2026年度<em>员工</em><em>持股</em>计划管理委员会委员的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467408.PDF"
    },
    {
      "id": "1225466767",
      "code": "301602",
      "name": "超研股份",
      "city": "广东汕头",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "关于<em>员工</em>战略配售资管计划减<em>持股</em>份期限届满暨实施情况的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466767.PDF"
    },
    {
      "id": "1225465718",
      "code": "02359",
      "name": "药明康德",
      "city": "未知",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "(1) 建议采纳A股<em>员工</em><em>持股</em>计划 (2) 建议采纳A股<em>员工</em><em>持股</em>计划管理办法 (3) 建议",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465718.PDF"
    },
    {
      "id": "1225467570",
      "code": "01877",
      "name": "君实生物",
      "city": "未知",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "海外监管公告 - 上海君实生物医药科技股份有限公司关于股东<em>减持</em>股份结果公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467570.PDF"
    },
    {
      "id": "1225467428",
      "code": "300251",
      "name": "光线传媒",
      "city": "北京",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于公司原持股5%以上股东<em>减持</em>计划期限届满暨实施情况的公告",
      "date": "2026-08-10",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467428.PDF"
    },
    {
      "id": "1225467006",
      "code": "300581",
      "name": "晨曦航空",
      "city": "陕西西安",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "西安晨曦航空科技股份有限公司关于控股股东<em>减持</em>计划期限届满的公告",
      "date": "2026-08-10",
      "star": 4,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467006.PDF"
    },
    {
      "id": "1225467005",
      "code": "301632",
      "name": "广东建科",
      "city": "广东广州",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于公司董事 高级管理人员自愿承诺不<em>减持</em>公司股份的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467005.PDF"
    },
    {
      "id": "1225466844",
      "code": "300558",
      "name": "贝达药业",
      "city": "浙江杭州",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于股东<em>减持</em>股份计划期限届满暨实施情况的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466844.PDF"
    },
    {
      "id": "1225466633",
      "code": "300619",
      "name": "金银河",
      "city": "广东佛山",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于公司控股股东 实际控制人及其一致行动人提前终止<em>减持</em>股份计划暨<em>减持</em>股份结果的公告",
      "date": "2026-08-10",
      "star": 4,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466633.PDF"
    },
    {
      "id": "1225466442",
      "code": "301093",
      "name": "华兰股份",
      "city": "江苏无锡江阴",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于公司部分董事及高级管理人员股份<em>减持</em>计划实施完成的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466442.PDF"
    },
    {
      "id": "1225467002",
      "code": "01456",
      "name": "国联民生",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于以集中竞价交易方式<em>回购</em>公司A股<em>股份</em>方案的公告",
      "date": "2026-08-10",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467002.PDF"
    },
    {
      "id": "1225466826",
      "code": "300223",
      "name": "北京君正",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于公司<em>回购</em><em>股份</em>方案的公告",
      "date": "2026-08-10",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466826.PDF"
    },
    {
      "id": "1225466313",
      "code": "01170",
      "name": "信星集团",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "翌日披露报表-<em>股份</em><em>回购</em>",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466313.PDF"
    },
    {
      "id": "1225466129",
      "code": "301173",
      "name": "毓恬冠佳",
      "city": "上海",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>实施完成暨<em>股份</em>变动的公告",
      "date": "2026-08-10",
      "star": 4,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466129.PDF"
    },
    {
      "id": "1225466073",
      "code": "300573",
      "name": "兴齐眼药",
      "city": "辽宁沈阳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em><em>股份</em>注销完成暨<em>股份</em>变动的公告",
      "date": "2026-08-10",
      "star": 4,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466073.PDF"
    },
    {
      "id": "1225466030",
      "code": "300932",
      "name": "三友联众",
      "city": "广东东莞",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>实施完成暨<em>股份</em>变动的公告",
      "date": "2026-08-10",
      "star": 4,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466030.PDF"
    },
    {
      "id": "1225465978",
      "code": "300565",
      "name": "科信技术",
      "city": "广东深圳",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465978.PDF"
    },
    {
      "id": "1225465522",
      "code": "301022",
      "name": "海泰科",
      "city": "山东青岛",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用暂时<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465522.PDF"
    },
    {
      "id": "1225465468",
      "code": "300707",
      "name": "威唐工业",
      "city": "江苏无锡",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用暂时<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465468.PDF"
    },
    {
      "id": "1225465475",
      "code": "300463",
      "name": "迈克生物",
      "city": "四川成都",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465475.PDF"
    },
    {
      "id": "1225465443",
      "code": "301015",
      "name": "百洋医药",
      "city": "山东青岛",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于归还用于临时补充流动<em>资金</em>的<em>闲置</em>募集<em>资金</em>的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465443.PDF"
    },
    {
      "id": "1225465670",
      "code": "300429",
      "name": "强力新材",
      "city": "江苏常州",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "协议转让",
      "summary": "关于控股股东 实际控制人及其一致行动人<em>协议</em><em>转让</em>部分公司股份进展暨签订补充<em>协议</em>及权益变动的提示性公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465670.PDF"
    },
    {
      "id": "1225465820",
      "code": "300726",
      "name": "宏达电子",
      "city": "湖南株洲",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "股权转让",
      "summary": "关于放弃参股公司<em>股权</em><em>转让</em>优先购买权暨关联交易的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465820.PDF"
    },
    {
      "id": "1225466510",
      "code": "301197",
      "name": "工大科雅",
      "city": "河北石家庄",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "公开征集",
      "summary": "关于股东拟通过<em>公开</em><em>征集</em>转让方式转让公司股份的公告",
      "date": "2026-08-10",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225466510.PDF"
    }
  ],
  "2026-08-09": [
    {
      "id": "1225467405",
      "code": "920045",
      "name": "蘅东光",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励",
      "summary": "董事会薪酬与考核委员会关于公司2026年<em>股权激励</em>计划 草案 的核查意见",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467405.PDF"
    },
    {
      "id": "1225467404",
      "code": "920045",
      "name": "蘅东光",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励",
      "summary": "2026年<em>股权激励</em>计划  草案",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467404.PDF"
    },
    {
      "id": "1225467403",
      "code": "920045",
      "name": "蘅东光",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "2026年<em>股权激励</em>计划首次授予激励对象名单",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467403.PDF"
    },
    {
      "id": "1225467402",
      "code": "920045",
      "name": "蘅东光",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励",
      "summary": "2026年<em>股权激励</em>计划实施考核管理办法",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467402.PDF"
    },
    {
      "id": "1225467400",
      "code": "920045",
      "name": "蘅东光",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励",
      "summary": "广东华商律师事务所关于蘅东光通讯技术 深圳 股份有限公司2026年<em>股权激励</em>计划 草案 的法律意见书",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467400.PDF"
    },
    {
      "id": "1225467294",
      "code": "920274",
      "name": "宏裕包材",
      "city": "湖北宜昌",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "2026年<em>限制性</em><em>股票</em>激励计划授予的激励对象名单",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467294.PDF"
    },
    {
      "id": "1225467293",
      "code": "920274",
      "name": "宏裕包材",
      "city": "湖北宜昌",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "2026年<em>限制性</em><em>股票</em>激励计划实施考核管理办法",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467293.PDF"
    },
    {
      "id": "1225467292",
      "code": "920274",
      "name": "宏裕包材",
      "city": "湖北宜昌",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "2026年<em>限制性</em><em>股票</em>激励计划 草案",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467292.PDF"
    },
    {
      "id": "1225467291",
      "code": "920274",
      "name": "宏裕包材",
      "city": "湖北宜昌",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "2026年<em>限制性</em><em>股票</em>激励计划管理办法",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467291.PDF"
    },
    {
      "id": "1225467290",
      "code": "920274",
      "name": "宏裕包材",
      "city": "湖北宜昌",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "董事会薪酬与考核委员会关于2026年<em>限制性</em><em>股票</em>激励计划 草案 的核查意见",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467290.PDF"
    },
    {
      "id": "1225467289",
      "code": "920274",
      "name": "宏裕包材",
      "city": "湖北宜昌",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "北京海润天睿律师事务所关于湖北宏裕新型包材股份有限公司2026年<em>限制性</em><em>股票</em>激励计划 草案 的法律意见书",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467289.PDF"
    },
    {
      "id": "1225465363",
      "code": "688521",
      "name": "芯原股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "2026年<em>限制性</em><em>股票</em>激励计划首次授予部分激励对象名单",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465363.PDF"
    },
    {
      "id": "1225465362",
      "code": "688521",
      "name": "芯原股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "2026年<em>限制性</em><em>股票</em>激励计划 草案 摘要公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465362.PDF"
    },
    {
      "id": "1225465361",
      "code": "688521",
      "name": "芯原股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "2026年<em>限制性</em><em>股票</em>激励计划 草案",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465361.PDF"
    },
    {
      "id": "1225465357",
      "code": "688521",
      "name": "芯原股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "董事会薪酬与考核委员会关于公司 2026年<em>限制性</em><em>股票</em>激励计划 草案  及其摘要的核查意见",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465357.PDF"
    },
    {
      "id": "1225465353",
      "code": "688521",
      "name": "芯原股份",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "2026年<em>限制性</em><em>股票</em>激励计划实施考核管理办法",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465353.PDF"
    },
    {
      "id": "1225464854",
      "code": "001309",
      "name": "德明利",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "关于回购注销2023年和2024年<em>限制性</em><em>股票</em>激励计划部分<em>限制性</em><em>股票</em>完成的公告",
      "date": "2026-08-09",
      "star": 4,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225464854.PDF"
    },
    {
      "id": "1225464270",
      "code": "300623",
      "name": "捷捷微电",
      "city": "江苏南通启东",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "北京德恒律师事务所关于捷捷微电2026年<em>限制性</em><em>股票</em>激励计划的法律意见",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225464270.PDF"
    },
    {
      "id": "1225464269",
      "code": "300623",
      "name": "捷捷微电",
      "city": "江苏南通启东",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "江苏捷捷微电子股份有限公司董事会薪酬与考核委员会关于2026年<em>限制性</em><em>股票</em>激励计划相关事项的核查意见",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225464269.PDF"
    },
    {
      "id": "1225464268",
      "code": "300623",
      "name": "捷捷微电",
      "city": "江苏南通启东",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "江苏捷捷微电子股份有限公司2026年<em>限制性</em><em>股票</em>激励计划自查表",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225464268.PDF"
    },
    {
      "id": "1225464267",
      "code": "300623",
      "name": "捷捷微电",
      "city": "江苏南通启东",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "江苏捷捷微电子股份有限公司2026年<em>限制性</em><em>股票</em>激励计划实施考核管理办法",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225464267.PDF"
    },
    {
      "id": "1225464266",
      "code": "300623",
      "name": "捷捷微电",
      "city": "江苏南通启东",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "江苏捷捷微电子股份有限公司2026年<em>限制性</em><em>股票</em>激励计划 草案",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225464266.PDF"
    },
    {
      "id": "1225464265",
      "code": "300623",
      "name": "捷捷微电",
      "city": "江苏南通启东",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "江苏捷捷微电子股份有限公司2026年<em>限制性</em><em>股票</em>激励计划 草案 摘要",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225464265.PDF"
    },
    {
      "id": "1225467346",
      "code": "920735",
      "name": "德源药业",
      "city": "江苏连云港",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "股东<em>减持</em>股份结果公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467346.PDF"
    },
    {
      "id": "1225467337",
      "code": "920957",
      "name": "汉维科技",
      "city": "广东东莞",
      "mv": 0,
      "category": "增减持",
      "subType": "减持计划",
      "summary": "股东拟<em>减持</em>股份的预披露公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467337.PDF"
    },
    {
      "id": "1225467306",
      "code": "920592",
      "name": "华信永道",
      "city": "北京",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "持股5%以上股东<em>减持</em>股份结果公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467306.PDF"
    },
    {
      "id": "1225467316",
      "code": "920427",
      "name": "华维设计",
      "city": "江西南昌",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于参与中大监理要约<em>回购</em><em>股份</em>暨关联交易公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467316.PDF"
    },
    {
      "id": "1225465368",
      "code": "688080",
      "name": "映翰通",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于以集中竞价交易方式<em>回购</em><em>股份</em>的预案",
      "date": "2026-08-09",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465368.PDF"
    },
    {
      "id": "1225465344",
      "code": "600449",
      "name": "宁夏建材",
      "city": "宁夏回族自治区银川",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "宁夏建材关于以集中竞价交易方式<em>回购</em>公司<em>股份</em>方案的公告",
      "date": "2026-08-09",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465344.PDF"
    },
    {
      "id": "1225465328",
      "code": "688357",
      "name": "建龙微纳",
      "city": "河南洛阳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于以集中竞价交易方式<em>回购</em>公司<em>股份</em>比例达到1%暨<em>回购</em>进展公告",
      "date": "2026-08-09",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465328.PDF"
    },
    {
      "id": "1225465290",
      "code": "603381",
      "name": "永臻<em>股份</em>",
      "city": "江苏常州",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于以集中竞价交易方式首次<em>回购</em><em>股份</em>的进展公告",
      "date": "2026-08-09",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225465290.PDF"
    },
    {
      "id": "1225464222",
      "code": "002998",
      "name": "优彩资源",
      "city": "江苏无锡江阴",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于注销<em>回购</em><em>股份</em>并变更注册资本暨通知债权人的公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225464222.PDF"
    },
    {
      "id": "1225467326",
      "code": "920374",
      "name": "云里物里",
      "city": "广东深圳",
      "mv": 0,
      "category": "委托理财",
      "subType": "委托理财",
      "summary": "关于使用部分闲置自有资金<em>委托</em><em>理财</em>的进展公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467326.PDF"
    },
    {
      "id": "1225467299",
      "code": "920061",
      "name": "西磁科技",
      "city": "浙江宁波",
      "mv": 0,
      "category": "委托理财",
      "subType": "委托理财",
      "summary": "自有闲置资金<em>委托</em><em>理财</em>进展公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467299.PDF"
    },
    {
      "id": "1225467287",
      "code": "920065",
      "name": "千岸科技",
      "city": "未知",
      "mv": 0,
      "category": "委托理财",
      "subType": "委托理财",
      "summary": "自有资金<em>委托</em><em>理财</em>进展公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467287.PDF"
    },
    {
      "id": "1225467388",
      "code": "920304",
      "name": "迪尔化工",
      "city": "山东泰安",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用<em>闲置</em>自有<em>资金</em>购买理财产品的公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467388.PDF"
    },
    {
      "id": "1225467387",
      "code": "920304",
      "name": "迪尔化工",
      "city": "山东泰安",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "中泰证券股份有限公司关于山东华阳迪尔化工股份有限公司使用<em>闲置</em>自有<em>资金</em>购买理财产品的核查意见",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467387.PDF"
    },
    {
      "id": "1225467373",
      "code": "920751",
      "name": "惠同新材",
      "city": "湖南长沙",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "中国国际金融股份有限公司关于湖南惠同新材料股份有限公司使用<em>闲置</em>募集<em>资金</em>进行现金管理的核查意见",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467373.PDF"
    },
    {
      "id": "1225467369",
      "code": "920751",
      "name": "惠同新材",
      "city": "湖南长沙",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用<em>闲置</em>募集<em>资金</em>进行现金管理的公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467369.PDF"
    },
    {
      "id": "1225467361",
      "code": "920008",
      "name": "成电光信",
      "city": "四川成都",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于<em>闲置</em>募集<em>资金</em>暂时补充流动<em>资金</em>归还的公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467361.PDF"
    },
    {
      "id": "1225467344",
      "code": "920656",
      "name": "海昇药业",
      "city": "浙江衢州",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467344.PDF"
    },
    {
      "id": "1225467341",
      "code": "920189",
      "name": "康美特",
      "city": "未知",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "广发证券股份有限公司关于北京康美特科技股份有限公司使用<em>闲置</em>募集<em>资金</em>进行现金管理的核查意见",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467341.PDF"
    },
    {
      "id": "1225467339",
      "code": "920189",
      "name": "康美特",
      "city": "未知",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>进行现金管理的公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467339.PDF"
    },
    {
      "id": "1225467327",
      "code": "920374",
      "name": "云里物里",
      "city": "广东深圳",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分暂时<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467327.PDF"
    },
    {
      "id": "1225467283",
      "code": "920124",
      "name": "南特科技",
      "city": "广东珠海",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分暂时<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225467283.PDF"
    },
    {
      "id": "1225463998",
      "code": "002261",
      "name": "拓维信息",
      "city": "湖南长沙",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "中信建投证券股份有限公司关于拓维信息系统股份有限公司使用部分暂时<em>闲置</em>募集<em>资金</em>进行现金管理的核查意见",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225463998.PDF"
    },
    {
      "id": "1225463997",
      "code": "002261",
      "name": "拓维信息",
      "city": "湖南长沙",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分暂时<em>闲置</em>募集<em>资金</em>进行现金管理的公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225463997.PDF"
    },
    {
      "id": "1225464399",
      "code": "300246",
      "name": "宝莱特",
      "city": "广东珠海",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "控制权变更",
      "summary": "关于终止筹划<em>控制权</em><em>变更</em>事项暨复牌及恢复转股的公告",
      "date": "2026-08-09",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-08-10/1225464399.PDF"
    }
  ]
};
