// 资本动作数据 - 2026-06-15 18:07
window.__CAPITAL_DATA__ = {
  "2026-06-15": [
    {
      "id": "1225372498",
      "code": "02196",
      "name": "复星医药",
      "city": "未知",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励",
      "summary": "海外监管公告 - 关于控股子公司<em>股权激励</em>实施进展暨关联交易的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372498.PDF"
    },
    {
      "id": "1225371632",
      "code": "300130",
      "name": "新国都",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股票期权",
      "summary": "董事会薪酬与考核委员会关于公司2026年<em>股票期权激励</em>计划激励对象名单的核查意见及公示情况说明",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371632.PDF"
    },
    {
      "id": "1225372286",
      "code": "301300",
      "name": "远翔新材",
      "city": "福建南平邵武",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "关于2023年<em>限制性</em><em>股票</em>激励计划第三个归属期归属结果暨股份上市的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372286.PDF"
    },
    {
      "id": "1225371960",
      "code": "301568",
      "name": "思泰克",
      "city": "福建厦门翔安区火炬高新区同翔高新城",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "关于公司2026年<em>限制性</em><em>股票</em>激励计划内幕信息知情人买卖公司<em>股票</em>情况的自查报告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371960.PDF"
    },
    {
      "id": "1225371986",
      "code": "301568",
      "name": "思泰克",
      "city": "福建厦门翔安区火炬高新区同翔高新城",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "董事会薪酬与考核委员会关于公司2026年<em>限制性</em><em>股票</em>激励计划首次授予激励对象名单 授予日 的核查意见",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371986.PDF"
    },
    {
      "id": "1225371985",
      "code": "301568",
      "name": "思泰克",
      "city": "福建厦门翔安区火炬高新区同翔高新城",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "北京海润天睿律师事务所关于厦门思泰克智能科技股份有限公司2026年<em>限制性</em><em>股票</em>激励计划首次授予的法律意见书",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371985.PDF"
    },
    {
      "id": "1225371984",
      "code": "301568",
      "name": "思泰克",
      "city": "福建厦门翔安区火炬高新区同翔高新城",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于向公司2026年<em>限制性</em><em>股票</em>激励计划激励对象首次授予<em>限制性</em><em>股票</em>的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371984.PDF"
    },
    {
      "id": "1225371557",
      "code": "300708",
      "name": "聚灿光电",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "董事会薪酬与考核委员会关于公司2025年<em>限制性</em><em>股票</em>激励计划首次授予部分第一个归属期归属名单的核查意见",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371557.PDF"
    },
    {
      "id": "1225371556",
      "code": "300708",
      "name": "聚灿光电",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于公司2025年<em>限制性</em><em>股票</em>激励计划首次授予部分第一个归属期归属条件成就的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371556.PDF"
    },
    {
      "id": "1225371555",
      "code": "300708",
      "name": "聚灿光电",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "董事会薪酬与考核委员会关于公司 2025年<em>限制性</em><em>股票</em>激励计划预留授予激励对象名单 授予日 的核查意见",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371555.PDF"
    },
    {
      "id": "1225371554",
      "code": "300708",
      "name": "聚灿光电",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "安徽天禾律师事务所关于聚灿光电科技股份有限公司2025年<em>限制性</em><em>股票</em>激励计划相关事项之法律意见书",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371554.PDF"
    },
    {
      "id": "1225371553",
      "code": "300708",
      "name": "聚灿光电",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "2025年<em>限制性</em><em>股票</em>激励计划预留授予激励对象名单 授予日",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371553.PDF"
    },
    {
      "id": "1225371552",
      "code": "300708",
      "name": "聚灿光电",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于向2025年<em>限制性</em><em>股票</em>激励计划激励对象预留授予<em>限制性</em><em>股票</em>的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371552.PDF"
    },
    {
      "id": "1225371550",
      "code": "300708",
      "name": "聚灿光电",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于调整2025年<em>限制性</em><em>股票</em>激励计划授予数量及价格的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371550.PDF"
    },
    {
      "id": "1225371549",
      "code": "300708",
      "name": "聚灿光电",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于作废部分已授予尚未归属的<em>限制性</em><em>股票</em>的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371549.PDF"
    },
    {
      "id": "1225371545",
      "code": "300195",
      "name": "长荣股份",
      "city": "天津",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于向2026年<em>限制性</em><em>股票</em>激励计划激励对象授予<em>限制性</em><em>股票</em>的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371545.PDF"
    },
    {
      "id": "1225371544",
      "code": "300195",
      "name": "长荣股份",
      "city": "天津",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "上海市广发律师事务所关于天津长荣科技集团股份有限公司2026年<em>限制性</em><em>股票</em>激励计划相关事项的法律意见",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371544.PDF"
    },
    {
      "id": "1225371543",
      "code": "300195",
      "name": "长荣股份",
      "city": "天津",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "董事会薪酬与考核委员会关于公司2026年<em>限制性</em><em>股票</em>激励计划相关事项的核查意见",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371543.PDF"
    },
    {
      "id": "1225371542",
      "code": "300195",
      "name": "长荣股份",
      "city": "天津",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "关于调整2026年<em>限制性</em><em>股票</em>激励计划相关事项的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371542.PDF"
    },
    {
      "id": "1225371383",
      "code": "300907",
      "name": "康平科技",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "董事会薪酬与考核委员会关于2026年<em>限制性</em><em>股票</em>激励计划首次授予相关事项的核查意见",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371383.PDF"
    },
    {
      "id": "1225371382",
      "code": "300907",
      "name": "康平科技",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于康平科技 苏州 股份有限公司首次授予<em>限制性</em><em>股票</em>事项的法律意见",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371382.PDF"
    },
    {
      "id": "1225371381",
      "code": "300907",
      "name": "康平科技",
      "city": "江苏苏州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于向2026年<em>限制性</em><em>股票</em>激励计划激励对象首次授予<em>限制性</em><em>股票</em>的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371381.PDF"
    },
    {
      "id": "1225371635",
      "code": "300999",
      "name": "金龙鱼",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "北京市汉坤律师事务所关于2022年<em>限制性</em><em>股票</em>激励计划调整授予价格及部分已授予尚未归属的<em>限制性</em><em>股票</em>作废的法律意见书",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371635.PDF"
    },
    {
      "id": "1225371633",
      "code": "300999",
      "name": "金龙鱼",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于公司2022年<em>限制性</em><em>股票</em>激励计划部分已授予尚未归属的<em>限制性</em><em>股票</em>作废 授予价格调整的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371633.PDF"
    },
    {
      "id": "1225370858",
      "code": "301221",
      "name": "光庭信息",
      "city": "湖北武汉",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于2025年<em>限制性</em><em>股票</em>激励计划首次授予部分第一个归属期归属结果暨股份上市的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370858.PDF"
    },
    {
      "id": "1225370645",
      "code": "300285",
      "name": "国瓷材料",
      "city": "山东东营",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "北京天达共和律师事务所关于山东国瓷功能材料股份有限公司2026年<em>限制性</em><em>股票</em>激励计划调整授予价格的法律意见书",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370645.PDF"
    },
    {
      "id": "1225370644",
      "code": "300285",
      "name": "国瓷材料",
      "city": "山东东营",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "董事会薪酬与考核委员会关于2025年年度权益分派实施后调整2026年<em>限制性</em><em>股票</em>激励计划授予价格的核查意见",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370644.PDF"
    },
    {
      "id": "1225370643",
      "code": "300285",
      "name": "国瓷材料",
      "city": "山东东营",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于2025年年度权益分派实施后调整2026年<em>限制性</em><em>股票</em>激励计划授予价格的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370643.PDF"
    },
    {
      "id": "1225370532",
      "code": "300337",
      "name": "银邦股份",
      "city": "江苏无锡",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "银邦股份关于2026年<em>限制性</em><em>股票</em>激励计划内幕信息知情人及激励对象买卖公司<em>股票</em>情况的自查报告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370532.PDF"
    },
    {
      "id": "1225370531",
      "code": "300337",
      "name": "银邦股份",
      "city": "江苏无锡",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "银邦股份董事会薪酬与考核委员会关于2026年<em>限制性</em><em>股票</em>激励计划激励对象名单的核查意见及公示情况说明",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370531.PDF"
    },
    {
      "id": "1225371686",
      "code": "300232",
      "name": "洲明科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "关于第七期<em>员工</em><em>持股</em>计划购买完成的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371686.PDF"
    },
    {
      "id": "1225371075",
      "code": "301328",
      "name": "维峰电子",
      "city": "广东东莞",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "关于2024年<em>员工</em><em>持股</em>计划第一个锁定期解锁股票出售完毕的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371075.PDF"
    },
    {
      "id": "1225371074",
      "code": "301055",
      "name": "张小泉",
      "city": "浙江杭州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "关于2026年<em>员工</em><em>持股</em>计划完成股票非交易过户的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371074.PDF"
    },
    {
      "id": "1225372404",
      "code": "301580",
      "name": "爱迪特",
      "city": "河北秦皇岛",
      "mv": 0,
      "category": "增减持",
      "subType": "减持计划",
      "summary": "关于持股5%以上股东<em>减持</em>股份预披露公告",
      "date": "2026-06-15",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372404.PDF"
    },
    {
      "id": "1225372313",
      "code": "300518",
      "name": "新迅达",
      "city": "广东深圳",
      "mv": 0,
      "category": "增减持",
      "subType": "减持计划",
      "summary": "关于持股5%以上股东<em>减持</em>计划预披露的公告",
      "date": "2026-06-15",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372313.PDF"
    },
    {
      "id": "1225372153",
      "code": "300063",
      "name": "天龙集团",
      "city": "广东肇庆",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于公司高级管理人员<em>减持</em>计划实施完毕的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372153.PDF"
    },
    {
      "id": "1225372069",
      "code": "300927",
      "name": "江天化学",
      "city": "江苏南通",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于持股5%以上股东<em>减持</em>计划实施完成的公告",
      "date": "2026-06-15",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372069.PDF"
    },
    {
      "id": "1225371461",
      "code": "300519",
      "name": "新光药业",
      "city": "浙江绍兴嵊州",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于公司持股5%以上股东<em>减持</em>股份触及1%整倍数的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371461.PDF"
    },
    {
      "id": "1225370811",
      "code": "301333",
      "name": "诺思格",
      "city": "北京",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于控股股东未<em>减持</em>公司股份并提前终止<em>减持</em>计划的公告",
      "date": "2026-06-15",
      "star": 4,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370811.PDF"
    },
    {
      "id": "1225370809",
      "code": "301390",
      "name": "经纬股份",
      "city": "浙江杭州",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于董事 高级管理人员股份<em>减持</em>期限届满暨<em>减持</em>结果的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370809.PDF"
    },
    {
      "id": "1225370782",
      "code": "301128",
      "name": "强瑞技术",
      "city": "广东深圳",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于控股股东及其一致行动人<em>减持</em>股份变动触及1%及5%整数倍暨披露简式权益变动报告书的提示性公告",
      "date": "2026-06-15",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370782.PDF"
    },
    {
      "id": "1225370778",
      "code": "300214",
      "name": "日科化学",
      "city": "山东潍坊",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于持股5%以上股东<em>减持</em>计划时间届满暨<em>减持</em>结果的公告",
      "date": "2026-06-15",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370778.PDF"
    },
    {
      "id": "1225370786",
      "code": "301281",
      "name": "科源制药",
      "city": "山东济南",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于特定股东股份<em>减持</em>计划实施完毕的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370786.PDF"
    },
    {
      "id": "1225370612",
      "code": "300985",
      "name": "致远新能",
      "city": "吉林长春",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "关于控股股东之一致行动人<em>减持</em>股份触及1%整数倍的公告",
      "date": "2026-06-15",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370612.PDF"
    },
    {
      "id": "1225372097",
      "code": "300193",
      "name": "佳士科技",
      "city": "广东深圳",
      "mv": 0,
      "category": "增减持",
      "subType": "增持",
      "summary": "关于实际控制人<em>增</em><em>持</em>公司股份的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372097.PDF"
    },
    {
      "id": "1225370529",
      "code": "300883",
      "name": "龙利得",
      "city": "安徽滁州明光",
      "mv": 0,
      "category": "增减持",
      "subType": "增持",
      "summary": "关于控股股东<em>增</em><em>持</em>公司股份计划实施进展暨权益变动触及1%整数倍的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370529.PDF"
    },
    {
      "id": "1225372669",
      "code": "02276",
      "name": "康耐特光学",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "自愿公告 - 完成2026年4月H股<em>回购</em>方案及注销已<em>回购</em><em>股份</em>",
      "date": "2026-06-15",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372669.PDF"
    },
    {
      "id": "1225372457",
      "code": "00018",
      "name": "东方传媒集团",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "有关一间附属公司进行<em>股份</em><em>回购</em>之关连交易",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372457.PDF"
    },
    {
      "id": "1225372304",
      "code": "02039",
      "name": "中集集团",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "自愿性公告 - <em>回购</em>部分H股<em>股份</em> 第二批 实施完成的公告",
      "date": "2026-06-15",
      "star": 4,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372304.PDF"
    },
    {
      "id": "1225371731",
      "code": "00386",
      "name": "中国石油化工<em>股份</em>",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告 - 中国石油化工<em>股份</em>有限公司关于以集中竞价交易方式<em>回购</em> A 股<em>股份</em>的<em>回购</em>报告书",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371731.PDF"
    },
    {
      "id": "1225371559",
      "code": "301223",
      "name": "中荣<em>股份</em>",
      "city": "广东中山",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>方案的公告",
      "date": "2026-06-15",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371559.PDF"
    },
    {
      "id": "1225371558",
      "code": "301223",
      "name": "中荣<em>股份</em>",
      "city": "广东中山",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "<em>回购</em>报告书",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371558.PDF"
    },
    {
      "id": "1225371657",
      "code": "00386",
      "name": "中国石油化工<em>股份</em>",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "海外监管公告 - 中国石油化工<em>股份</em>有限公司关于<em>回购</em><em>股份</em>通知债权人的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371657.PDF"
    },
    {
      "id": "1225370812",
      "code": "301333",
      "name": "诺思格",
      "city": "北京",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em>公司<em>股份</em>方案的公告",
      "date": "2026-06-15",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370812.PDF"
    },
    {
      "id": "1225370802",
      "code": "300082",
      "name": "奥克<em>股份</em>",
      "city": "辽宁辽阳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于子公司江苏奥克拟与江苏扬州化学工业园区达成部分土地有偿<em>回购</em>交易的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370802.PDF"
    },
    {
      "id": "1225370536",
      "code": "301173",
      "name": "毓恬冠佳",
      "city": "上海",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em><em>股份</em>事项前十名股东及前十名无限售条件股东持股情况的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370536.PDF"
    },
    {
      "id": "1225370482",
      "code": "300787",
      "name": "海能实业",
      "city": "江西吉安",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于<em>回购</em><em>股份</em>事项前十名股东及前十名无限售条件股东持股情况的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370482.PDF"
    },
    {
      "id": "1225370481",
      "code": "300787",
      "name": "海能实业",
      "city": "江西吉安",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "关于首次<em>回购</em>公司<em>股份</em>的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370481.PDF"
    },
    {
      "id": "1225370321",
      "code": "00341",
      "name": "大家乐集团",
      "city": "未知",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "自愿公告 - 于公开市场<em>回购</em><em>股份</em>",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370321.PDF"
    },
    {
      "id": "1225370808",
      "code": "301027",
      "name": "华蓝集团",
      "city": "广西壮族自治区南宁",
      "mv": 0,
      "category": "委托理财",
      "subType": "委托理财",
      "summary": "关于公司及子公司使用闲置自有资金进行<em>委托</em><em>理财</em>的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370808.PDF"
    },
    {
      "id": "1225371298",
      "code": "300331",
      "name": "苏大维格",
      "city": "江苏苏州",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>进行现金管理及到期赎回的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371298.PDF"
    },
    {
      "id": "1225370932",
      "code": "300707",
      "name": "威唐工业",
      "city": "江苏无锡",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用暂时<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370932.PDF"
    },
    {
      "id": "1225370599",
      "code": "300943",
      "name": "春晖智控",
      "city": "浙江绍兴",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>和自有<em>资金</em>进行现金管理的进展公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370599.PDF"
    },
    {
      "id": "1225370381",
      "code": "301098",
      "name": "金埔园林",
      "city": "江苏南京",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分暂时<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370381.PDF"
    },
    {
      "id": "1225372710",
      "code": "02218",
      "name": "安德利果汁",
      "city": "未知",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "协议转让",
      "summary": "关于签署股权<em>转让</em>框架<em>协议</em>的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372710.PDF"
    },
    {
      "id": "1225372699",
      "code": "02218",
      "name": "安德利果汁",
      "city": "未知",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "协议转让",
      "summary": "内幕消息有关订立股权<em>转让</em>框架<em>协议</em>及可能收购宁波甬强科技有限公司控制权",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372699.PDF"
    },
    {
      "id": "1225372191",
      "code": "300072",
      "name": "海新能科",
      "city": "北京",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "股权转让",
      "summary": "关于<em>转让</em>控股子公司<em>股权</em>暨被动形成财务资助逾期的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372191.PDF"
    },
    {
      "id": "1225371636",
      "code": "300031",
      "name": "宝通科技",
      "city": "江苏无锡",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "股权转让",
      "summary": "关于全资子公司<em>股权</em><em>转让</em>暨交割完成的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371636.PDF"
    },
    {
      "id": "1225371547",
      "code": "300247",
      "name": "融捷健康",
      "city": "安徽合肥",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "股权转让",
      "summary": "关于<em>转让</em>参股公司部分<em>股权</em>的公告",
      "date": "2026-06-15",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371547.PDF"
    }
  ],
  "2026-06-14": [
    {
      "id": "1225371238",
      "code": "920069",
      "name": "XD普昂医",
      "city": "浙江杭州",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股票期权",
      "summary": "关于2024年<em>股权激励</em>计划第一个行权期部分股票期权注销完成的公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371238.PDF"
    },
    {
      "id": "1225370089",
      "code": "603683",
      "name": "晶华新材",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "晶华新材关于调整公司2024年限制性股票与<em>股票期权激励</em>计划之限制性股票回购价格 股票期权行权价格的公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370089.PDF"
    },
    {
      "id": "1225370086",
      "code": "603683",
      "name": "晶华新材",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "上海东方华银律师事务所关于晶华新材调整公司2024年限制性股票与<em>股票期权激励</em>计划之限制性股票回购价格 股票期权行权价格及注销部分股票期权与回购注销部分限制性股票之法律意见书",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370086.PDF"
    },
    {
      "id": "1225370129",
      "code": "603683",
      "name": "晶华新材",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "晶华新材关于注销部分<em>股票</em>期权与回购注销部分<em>限制性</em><em>股票</em>的公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370129.PDF"
    },
    {
      "id": "1225370094",
      "code": "603683",
      "name": "晶华新材",
      "city": "上海",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "晶华新材关于回购注销部分激励对象已获授但尚未解除限售的<em>限制性</em><em>股票</em>通知债权人的公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370094.PDF"
    },
    {
      "id": "1225369145",
      "code": "300992",
      "name": "泰福泵业",
      "city": "浙江台州温岭",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "关于公司2024年<em>限制性</em><em>股票</em>激励计划第二个归属期归属结果暨股份上市的公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225369145.PDF"
    },
    {
      "id": "1225368817",
      "code": "300498",
      "name": "温氏股份",
      "city": "广东云浮",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "限制性股票",
      "summary": "关于公司第四期<em>限制性</em><em>股票</em>激励计划部分激励对象自愿锁定部分股份承诺的公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225368817.PDF"
    },
    {
      "id": "1225368816",
      "code": "300498",
      "name": "温氏股份",
      "city": "广东云浮",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "股权激励授予",
      "summary": "关于公司第四期<em>限制性</em><em>股票</em>激励计划第二类<em>限制性</em><em>股票</em>首次授予部分第三个归属期 预留授予部分第",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225368816.PDF"
    },
    {
      "id": "1225372332",
      "code": "920374",
      "name": "云里物里",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "2026年<em>员工</em><em>持股</em>计划第一次持有人会议决议公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372332.PDF"
    },
    {
      "id": "1225372331",
      "code": "920374",
      "name": "云里物里",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "关于2026年<em>员工</em><em>持股</em>计划完成股票非交易过户的公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372331.PDF"
    },
    {
      "id": "1225372330",
      "code": "920374",
      "name": "云里物里",
      "city": "广东深圳",
      "mv": 0,
      "category": "股权激励/员工持股",
      "subType": "员工持股",
      "summary": "关于2024年<em>员工</em><em>持股</em>计划第二个解锁期届满暨解锁条件未成就的公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "代发薪酬资产引入|员工行权融资|股东账户开立",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372330.PDF"
    },
    {
      "id": "1225371724",
      "code": "920701",
      "name": "豪声电子",
      "city": "浙江嘉兴",
      "mv": 0,
      "category": "增减持",
      "subType": "减持计划",
      "summary": "股东拟<em>减持</em>股份的预披露公告 再次披露",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371724.PDF"
    },
    {
      "id": "1225371419",
      "code": "920111",
      "name": "聚星科技",
      "city": "浙江温州",
      "mv": 0,
      "category": "增减持",
      "subType": "减持计划",
      "summary": "股东拟<em>减持</em>股份的预披露公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371419.PDF"
    },
    {
      "id": "1225371379",
      "code": "920685",
      "name": "新芝生物",
      "city": "浙江宁波",
      "mv": 0,
      "category": "增减持",
      "subType": "减持",
      "summary": "股东<em>减持</em>股份结果公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "增减持产品（算法交易、场外期权）|专项融资|市值管理",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371379.PDF"
    },
    {
      "id": "1225372329",
      "code": "920374",
      "name": "云里物里",
      "city": "广东深圳",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "第三次竞价<em>回购</em><em>股份</em>方案暨<em>回购</em><em>股份</em>报告书的公告",
      "date": "2026-06-14",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372329.PDF"
    },
    {
      "id": "1225370107",
      "code": "600679",
      "name": "上海凤凰",
      "city": "上海",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "上海凤凰关于<em>回购</em>实施结果暨<em>股份</em>变动的公告",
      "date": "2026-06-14",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370107.PDF"
    },
    {
      "id": "1225370105",
      "code": "600109",
      "name": "国金证券",
      "city": "四川成都",
      "mv": 0,
      "category": "股份回购",
      "subType": "股份回购",
      "summary": "国金证券<em>股份</em>有限公司关于以集中竞价交易方式首次<em>回购</em>公司<em>股份</em>的公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "回购账户开立|回购融资|库存股再激励方案",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370105.PDF"
    },
    {
      "id": "1225371456",
      "code": "920414",
      "name": "欧普泰",
      "city": "上海",
      "mv": 0,
      "category": "委托理财",
      "subType": "委托理财",
      "summary": "关于使用自有资金<em>委托</em><em>理财</em>的进展公告",
      "date": "2026-06-14",
      "star": 3,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371456.PDF"
    },
    {
      "id": "1225372146",
      "code": "920455",
      "name": "汇隆活塞",
      "city": "辽宁大连",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "申万宏源证券承销保荐有限责任公司关于大连汇隆活塞股份有限公司使用部分<em>闲置</em>募集<em>资金</em>现金管理的核查意见",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372146.PDF"
    },
    {
      "id": "1225372145",
      "code": "920455",
      "name": "汇隆活塞",
      "city": "辽宁大连",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>募集<em>资金</em>现金管理的公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372145.PDF"
    },
    {
      "id": "1225372030",
      "code": "920925",
      "name": "锦好医疗",
      "city": "广东惠州",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用部分<em>闲置</em>自有<em>资金</em>购买理财产品的进展公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225372030.PDF"
    },
    {
      "id": "1225371317",
      "code": "920876",
      "name": "慧为智能",
      "city": "广东深圳",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用<em>闲置</em>自有<em>资金</em>进行现金管理的进展公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225371317.PDF"
    },
    {
      "id": "1225370420",
      "code": "920504",
      "name": "博迅生物",
      "city": "上海",
      "mv": 0,
      "category": "委托理财",
      "subType": "闲置资金",
      "summary": "关于使用<em>闲置</em>募集<em>资金</em>进行现金管理的进展公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "收益凭证定制|闲置资金资产配置|结构性存款引入",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370420.PDF"
    },
    {
      "id": "1225370210",
      "code": "605298",
      "name": "必得科技",
      "city": "江苏无锡江阴",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "协议转让",
      "summary": "江苏必得科技股份有限公司关于公司股东<em>协议</em><em>转让</em>股份的公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370210.PDF"
    },
    {
      "id": "1225370159",
      "code": "300681",
      "name": "英搏尔",
      "city": "广东珠海",
      "mv": 0,
      "category": "协议转让/控制权变更",
      "subType": "股权转让",
      "summary": "关于全资子公司<em>股权</em><em>转让</em>完成的公告",
      "date": "2026-06-14",
      "star": 2,
      "claimed": false,
      "claimDept": "",
      "direction": "并购财务顾问|控制权转让撮合|大宗减持税务筹划",
      "url": "https://static.cninfo.com.cn/finalpage/2026-06-15/1225370159.PDF"
    }
  ]
};
